---
- hosts: all
  vars_files:
    - vars.yml
  sudo: true
  sudo_user: root

  tasks:  
    - name: clone project repo in destination
      git: repo={{ project_repo }} dest={{ project_root }} accept_hostkey=true
      
    - name: install npm
      npm: path=/var/projects/mysampleproject/example
      
    - name: run the app
      command: forever start /var/projects/mysampleproject/example/app_with_feature.js 162.243.109.180
   
